### ISSUE TITLE
I need to install 1.3, how to do that with cocoapods?

### ISSUE THREAD

**Issue by applebeast** [lorentey/BigInt#16]
I can't download 1.3 with  cocoapods, whenever I build my  xcode workspace, it says "no such module bigint"

**Comment by lorentey** [comment]
I don't have the resources to provide free support for previous releases. BigInt 1.3 uses Swift 2.2, which makes it especially painful in this regard.

If there is a bug in v1.3's CocoaPods support, then that's unfortunate. I'm happy to accept a pull request to fix it, and to do the maintenance work of releasing version 1.3.1 with the bugfix. But you'll have to debug and fix the bug on your own. (Start by looking into the build logs; there is probably an earlier error message that indicates the actual problem.)

If this is for a commercial project, then of course you also have the option to contract me to fix the bug for you as a consultant. Contact me by email if that's the case.
