### ISSUE TITLE
Using extremely small number

### ISSUE THREAD

**Issue by nikhilpandey4** [lorentey/BigInt#17]
Hi
I want something like pow(0.5, 1000). How is this possible using BigInt

**Comment by lorentey** [comment]
BigInt is all about integers, so there is no support for that.

However, you can use BigInt to implement arbitrary precision floating point numbers or rational numbers. For example, you could define a rational type like

```swift
struct Rational {
    let sign: Sign
    let nominator: BigUInt
    let denominator: BigUInt
}
```

And then go on defining all the usual operations on `Rational`: `+`, `-`, `*`, `/`, and, of course, even `power`. (0.5 to the power of 1000 would be equal to `Rational(sign: .plus, nominator: 1, denominator: 2 << 1000)`)

**Comment by nikhilpandey4** [comment]
Hi
Thanks for your prompt reply. Highly appreciated. Request you to show how this can be implemented in Swift using BigInt as this is one of the important things for which people need arbitrary precision. Also request you to put an example in your gitrepo for something like binomial coefficients.
