### ISSUE TITLE
BigUInt to UInt8

### ISSUE THREAD

**Issue by beartiago** [lorentey/BigInt#3]
is there anyway of converting a BigUInt to [UInt8]?

**Comment by lorentey** [comment]
Sure! You can use the `serialize` method to convert it into an `NSData` (or `Data` on the `swift3` branch):

http://lorentey.github.io/BigInt/api/Structs/BigUInt.html#/s:FV6BigInt7BigUInt9serializeFS0_FT_CSo6NSData

The returned data consists of the base-256 representation in big-endian order.
