### ISSUE TITLE
versioning scheme to use with spm

### ISSUE THREAD

**Issue by ratranqu** [lorentey/BigInt#4]
Would it be possible to comply to the semVer semantic scheme for versioning so that the swift package manager can be used?
(https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md#version)
(http://semver.org)

many thx!

**Comment by lorentey** [comment]
What exactly do I need to do for this? I thought I was already using semantic versioning. :-)

**Comment by lorentey** [comment]
Where? The version tags are all in "vx.y.z" format.

**Comment by lorentey** [comment]
Oh wait, do you mean I should remove the v?

**Comment by ratranqu** [comment]
Yes :). I think having the v is actually what GitHub recommends, but the spm expects x.y.z with possible suffixes. No prefixes.

**Comment by lorentey** [comment]
Are you sure? It has explicit code to handle v-prefixed version tags, I believe exactly for this reason:

https://github.com/apple/swift-package-manager/blob/master/Sources/Utility/Git.swift

Renaming the tags would be simple enough, but I don't know what side-effects that may produce. (An avalanche of Travis builds for ancient code is definitely one. Also, the tag is encoded in documentation links.)

**Comment by ratranqu** [comment]
Hum... I have to say I am not 100% certain. I thought it was the case (at least in the in the past). Maybe it works now. In the case that it does not work with v prefixes though, I don't think you should change any existing tags. Just add new ones on the new format (or both) going forward.

**Comment by lorentey** [comment]
v-prefixed tags worked fine in the initial couple of months of SPM, and I remember they were documented to work. I haven't recently used the package manager, so I don't know if they're broken now. I'll run a quick check now, and if they are, I'll file a bug report with SPM. (Current SPM documentation seems to be practically nonexistent.)

I believe it would be unreasonable for SPM to change its version tagging requirements, but if they insist, I'll use naked numbers in future releases.

**Comment by lorentey** [comment]
Good news! The current version of SPM still has no trouble finding the correct tag with a `Package.swift` such as the one below:

```
let package = Package(
    name: "Foobar",
    dependencies: [
      .Package(url: "https://github.com/lorentey/BigInt.git", Version(2, 0, 0)),
    ]
)
```

**Comment by ratranqu** [comment]
Super. Sorry for hassle. My mistake.

**Comment by lorentey** [comment]
No worries!
