### ISSUE TITLE
ShiftOperations Exposure

### ISSUE THREAD

**Issue by nvzqz** [lorentey/BigInt#9]
I like the idea of a `ShiftOperations` protocol that's essentially a cousin of `BitwiseOperations`. However, I feel as though the `ShiftOperations` protocol is outside of the scope of `BigInt`.

I made a [separate module](https://github.com/nvzqz/ShiftOperations) that simply contains this protocol. I make good use of it in https://github.com/nvzqz/RandomKit/commit/4fdd456c70e5ecbd91c982143d779941165cfb22. Perhaps BigInt can import this module to satisfy that protocol?

If that isn't the direction you'd want to go, I feel as though `ShiftOperations` should at least have an `internal` access level rather than `public` because it is only used by `BigDigit`.

**Comment by lorentey** [comment]
You're right, `ShiftOperations` shouldn't be public. In fact, it should probably be removed & its members should be moved into `BigDigit`. This will require a major version bump.

**Comment by nvzqz** [comment]
If you intend on making breaking changes, don't forget to fix [this](https://github.com/lorentey/BigInt/blob/master/sources/BigUInt%20Random.swift#L61-L68) method signature :wink:

**Comment by lorentey** [comment]
Hm, two things seem worth creating a branch for.

My current plan is to release BigInt 3.0 when SE-0104 gets implemented, unless it gets pushed to phase two of Swift 4 or later.

**Comment by nvzqz** [comment]
Yeah, I was hoping for a `BinaryInteger` implementation in Swift 3 and was pretty disappointed it didn't happen then.
